# Site settings
title: hygiene-check.net
subtitle: die Coronachecker
email: services@hygiene-profis.net
description: Ihre Hygienprofis
baseurl: "/hygiene_check_net" # the subpath of your site, e.g. /blog
url: "https://kilianmh.github.io" # the base hostname & protocol for your site
author: Susana Montoro y Stingl, Joachim H&auml;mmerle
street_address: Krummestraße 1B
city: Schwanau
state: Baden-Württemberg
zip_code: 77963
country: Deutschland
phone: 017684905537

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
